export class OutboundMessageProcessor {
    readonly socket: WebSocket;

    constructor(socket: WebSocket) {
        this.socket = socket;
    }

    /**
     * Sends join lobby code
     * @returns Ship id generated by server
     */
    public sendJoin(): string {}
}
